# Lab 2.1: Introduction to NumPy

**Name:** Zubair Moeen  
**Reg Number:** 22jzele0463  
**Lab:** Machine Learning Lab  
**Lab Supervisor:** Engr.Irshad Ullah  
**University:** UET Peshawar - Campus Nowshera

## Lab Overview
This notebook covers the basic use of NumPy for numerical computing in Python. The code demonstrates array creation, array properties, indexing, slicing, reshaping, and basic matrix operations.

## Learning Objectives
- Import and use the NumPy library with the standard alias np.
- Create one-dimensional and multi-dimensional arrays from Python lists.
- Understand array shape, indexing, slicing, and reshaping operations.
- Practice basic numerical and matrix operations used in machine learning preprocessing.


## Section 1: NumPy Setup and Array Creation
This section starts with importing NumPy and creating arrays from Python lists. These are the basic building blocks used later in machine learning datasets.


# Introduction to Numpy module:
NumPy is a powerful Python library for numerical computing, providing support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays efficiently. It serves as the foundation for many scientific and mathematical Python libraries due to its speed and versatility. NumPy offers capabilities for array manipulation, mathematical operations, linear algebra, random number generation, and more, making it an essential tool for data manipulation and analysis in fields such as machine learning, data science, and engineering. With its efficient implementation in C, NumPy facilitates fast computations and enables seamless integration with other Python libraries and tools. Its simplicity and performance make it a cornerstone of the Python scientific computing ecosystem.






### Installation
We can easily install this library using the terminal. Follow the steps given below to install Numpy:<br>
Step 1: Go to the Windows PowerShell.<br>
Step 2: We can install Numpy with the help of pip easily. Head over to the directory where you want to install the numpy and fire the below command:<br>
__pip install numpy__<br>
__OR__<br>
__conda install numpy__<br>
This is very simple to install. tall.

# import numpy
Once numpy is installed, import it in your applications by adding the import keyword:<br>
__import numpy as pd__<br>
Now numpy is imported and ready to use.

In [2]:
import numpy as np

#### 1.1 Creating an array from list

In [3]:
mylist=[1,3,5,6]

In [4]:
type(mylist)

list

Converting the simple list to numpy array

In [5]:
np.array(mylist)

array([1, 3, 5, 6])

In [6]:
type(mylist)

list

What happens in the above code ??

In [7]:
arr=np.array(mylist)

In [8]:
arr

array([1, 3, 5, 6])

### 1.2 Creating matrix 

In [9]:
mylist=[[1,3,5],[4,5,6],[1,4,76],[1,3,5]]

In [10]:
mylist

[[1, 3, 5], [4, 5, 6], [1, 4, 76], [1, 3, 5]]

In [11]:
np.array(mylist)

array([[ 1,  3,  5],
       [ 4,  5,  6],
       [ 1,  4, 76],
       [ 1,  3,  5]])

In [12]:
mymatrix = np.array(mylist)

In [13]:
mymatrix.shape

(4, 3)

In [14]:
mynewmatrix = np.array(mylist)
mynewmatrix

array([[ 1,  3,  5],
       [ 4,  5,  6],
       [ 1,  4, 76],
       [ 1,  3,  5]])

### 1.3 Creating the numpy array by using range function

In [15]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [16]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### 1.4 Creating the numpy array of only Zeros by using range function 

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

### 1.5 Creating the matrix of only Zeros

In [18]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### 1.6 Creating the matrix of only 1

In [19]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Some operation

In [20]:
np.ones((5,5)) +5

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [21]:
np.ones(4)*100

array([100., 100., 100., 100.])

In [22]:
np.ones(4)/100

array([0.01, 0.01, 0.01, 0.01])

### 1.7 Creating of array by using linespace function 
The general syntax of numpy.linspace() is numpy.linspace(start, stop, num=50). It generates an array of evenly spaced numbers over a specified interval [start, stop], inclusive of both endpoints, with the number of elements determined by num.

In [23]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
len(np.linspace(0,10,20))

20

### 1.8 Eye function 

A function with 1 on the priciple diagnol

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 1.9 Random numbers

In [26]:
np.random.rand(5)

array([0.97313329, 0.00390207, 0.16859352, 0.86656567, 0.534835  ])

In [27]:
np.random.rand(3,5)

array([[0.45668569, 0.6440898 , 0.73474314, 0.36827248, 0.60319292],
       [0.92121259, 0.71248841, 0.41813175, 0.69589821, 0.92516092],
       [0.93709119, 0.29822183, 0.71409566, 0.89223594, 0.17292256]])

In [28]:
np.random.randint(1,100,5)

array([91,  8, 95,  9, 84], dtype=int32)

#### How Random Seed Works (NumPy)

np.random.seed(x) resets the random number generator to a fixed starting point.

Using the same seed → produces the same random numbers every time.

Seed affects only the next random operations after it is called.

In Jupyter Notebook, each cell continues the same random sequence.

So, if you set the seed in one cell and generate numbers in another, the result will change.

To get identical output in different cells, set the seed again before each random operation.

In [29]:
np.random.seed(24)
a = np.random.rand(4)
a

array([0.9600173 , 0.69951205, 0.99986729, 0.2200673 ])

In [30]:
b = np.random.rand(4)
b

array([0.36105635, 0.73984099, 0.99645573, 0.31634698])

In [31]:
arr1=np.random.randint(0,50,16)
arr1

array([35, 15, 39,  9, 18,  7, 25, 35, 45, 31, 28,  0, 12, 31, 33,  1],
      dtype=int32)

In [32]:
arr1.shape

(16,)

#### reshape

In [33]:
arr1.reshape(4,4)

array([[35, 15, 39,  9],
       [18,  7, 25, 35],
       [45, 31, 28,  0],
       [12, 31, 33,  1]], dtype=int32)

# 2 numpy indeximg, slicing, and selection

In [34]:
import numpy as np

In [35]:
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr[8]

np.int64(8)

## Section 2: Array Attributes, Indexing, and Slicing
The following cells inspect array dimensions, shapes, and selected values. This is important for understanding how ML data is stored and accessed.


In [37]:
arr[2]

np.int64(2)

In [38]:
arr[1:5]

array([1, 2, 3, 4])

In [39]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [41]:
arr[:5]

array([0, 1, 2, 3, 4])

In [42]:
arr[4:7]

array([4, 5, 6])

In [43]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

### Broadcasting

In [44]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [45]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

print(A + b)


[[11 22 33]
 [14 25 36]]


In [46]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [47]:
arr+100 / 2

array([50., 51., 52., 53., 54., 55., 56., 57., 58., 59., 60.])

In [48]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

## INDEXING on 2D array
## Run and observe the following code

In [49]:
arr_2d=np.array([[1,45,5],[2,45,6],[7,8,9]])
arr_2d

array([[ 1, 45,  5],
       [ 2, 45,  6],
       [ 7,  8,  9]])

In [50]:
arr_2d.shape


(3, 3)

In [51]:
arr_2d[1]

array([ 2, 45,  6])

In [52]:
arr_2d[1][0]

np.int64(2)

In [53]:
arr_2d[1][1]

np.int64(45)

In [54]:
arr_2d[1,1]

np.int64(45)

In [55]:
arr_2d

array([[ 1, 45,  5],
       [ 2, 45,  6],
       [ 7,  8,  9]])

In [56]:
arr_2d[:2]

array([[ 1, 45,  5],
       [ 2, 45,  6]])

In [57]:
arr_2d[:2,1:]

array([[45,  5],
       [45,  6]])

## Boolean Indexing (or Boolean Masking) in NumPy

In [58]:
arr=np.arange(6)

In [59]:
arr

array([0, 1, 2, 3, 4, 5])

In [60]:
arr < 4

array([ True,  True,  True,  True, False, False])

In [61]:
arr > 4

array([False, False, False, False, False,  True])

## Condition seletion

In [62]:
bool_arr= arr>4

In [63]:
bool_arr

array([False, False, False, False, False,  True])

In [64]:
arr[bool_arr]  #condition seletion

array([5])

In [65]:
arr[arr>4]

array([5])

In [66]:
arr[arr ==2]

array([2])

In [67]:
arr[arr <=4]

array([0, 1, 2, 3, 4])

## Some mathimathical operations

In [68]:
arr = np.array([1,4,9]) 

In [69]:
np.sqrt(arr)

array([1., 2., 3.])

In [70]:
np.log(arr) #bcz first no is zro its makes it infinity

array([0.        , 1.38629436, 2.19722458])

In [71]:
np.sin(arr)

array([ 0.84147098, -0.7568025 ,  0.41211849])

In [72]:
arr.sum()

np.int64(14)

In [73]:
arr.max()

np.int64(9)

In [74]:
arr.mean()

np.float64(4.666666666666667)

In [75]:
arr_2d=np.array([[1,2,3],[2,2,3],[4,1,1]])

In [76]:
arr_2d

array([[1, 2, 3],
       [2, 2, 3],
       [4, 1, 1]])

In [77]:
arr_2d.sum()

np.int64(19)

In [78]:
arr_2d.shape

(3, 3)

In [79]:
# give me sum acroos the rows
arr_2d.sum(axis=0) 
    #array  along the vertical axis when axis=0 that count colum element
  #mean that produce the sum of the coluam  

array([7, 5, 7])

In [80]:
arr_2d.sum(axis=1)

array([6, 7, 6])

# 3 NumPy Statistical Functions

In [81]:
import numpy as np

arr = np.array([4, 9, 2, 7, 5])
print("Array:", arr)

# Mean
print("Mean:", arr.mean())

# Maximum value
print("Max:", arr.max())

# Minimum value
print("Min:", arr.min())

# Index of maximum value
print("Argmax:", arr.argmax())

# Index of minimum value
print("Argmin:", arr.argmin())

# Standard deviation
print("Standard Deviation:", arr.std())

# Variance
print("Variance:", arr.var())

# Median
print("Median:", np.median(arr))

# Sum of all elements
print("Sum:", arr.sum())

# Cumulative sum
print("Cumulative Sum:", arr.cumsum())

# Sorting
print("Sorted Array:", np.sort(arr))


Array: [4 9 2 7 5]
Mean: 5.4
Max: 9
Min: 2
Argmax: 1
Argmin: 2
Standard Deviation: 2.4166091947189146
Variance: 5.84
Median: 5.0
Sum: 27
Cumulative Sum: [ 4 13 15 22 27]
Sorted Array: [2 4 5 7 9]


## Section 3: Matrix and Numerical Operations
The remaining examples practice numerical operations on arrays and matrices. These operations are commonly used before applying ML models.


## numpy exericses 

In [82]:
import numpy as np

## create an array of 10 zeros

In [83]:
arr=np.zeros(10)

In [84]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## create an array of 10 ones

In [85]:
arr=np.ones(10)

In [86]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## create an array of 10 fives 

In [87]:
arr=np.ones(10)*5

In [88]:
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## create an array of  integer  from 10 to 50

In [89]:
arr=np.arange(10,51)

In [90]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

## create an array of all even integer from 10 to 50

In [91]:
arr=np.arange(10,51,2)

In [92]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

## create 3x3 matrix with the values ranging of 0 to 8

In [93]:
arr=np.array([[0,1,2],[3,4,5],[6,7,8]])

In [94]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [95]:
matrix = np.arange(9).reshape((3, 3))

In [96]:
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [97]:
matrix = np.arange(16)
matrix.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## create 3x3 identity matrix

In [98]:
identity_matrix = np.identity(3)
identity_matrix 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [99]:
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [100]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [101]:
arr=np.random.rand(1)

In [102]:
arr

array([0.53503753])

In [103]:
random_matrix = np.random.randn(25)

In [104]:
random_matrix

array([-0.05813086,  0.58860351,  0.79823053, -1.94995143, -2.1628745 ,
        0.1732177 ,  0.44980691, -0.15639909, -0.5017551 , -1.13070873,
       -2.29896186,  0.69752566, -1.17402782, -0.73272521, -1.984332  ,
        0.26950264, -0.77941255,  0.8706628 , -0.32149986,  1.9582427 ,
        1.79617509,  1.352329  , -0.38124668,  0.36649793,  0.99719722])

In [105]:
arr=np.arange(1,101)

In [106]:
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [107]:
arr=np.arange(1,101)/100
arr.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [108]:
arr

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

## create an arry of 20 linearly spaced point b/w 0 and 1

In [109]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## numpy indexing and selection

In [110]:
mat=np.arange(1,26).reshape(5,5)

In [111]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [112]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [113]:
mat[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [114]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [115]:
mat[3,4]

np.int64(20)

In [116]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [117]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [118]:
mat.sum()

np.int64(325)

In [119]:
mat.std()

np.float64(7.211102550927978)

In [120]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [121]:
np.random.seed(101)

In [122]:
np.random.rand(1)

array([0.51639863])

## Final Conclusion
In this lab, NumPy was used to create and manipulate arrays. These concepts are useful for handling numerical data before applying machine learning algorithms.